import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.KotlinJvmProjectExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/current/samples
 */

plugins {
    val kotlinVersion = "2.4.10"
    kotlin("jvm") version kotlinVersion
    id("com.gradleup.shadow") version "9.6.1"
}

allprojects {
    apply {
        plugin("org.jetbrains.kotlin.jvm")
        plugin("com.gradleup.shadow")
    }

    group = "io.github.clayclaw"

    val spigotVersion = "26.2-R0.1-SNAPSHOT"

    extensions.configure<KotlinJvmProjectExtension> {
        jvmToolchain(25)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_25)
        }
    }

    repositories {
        mavenCentral()
        maven {
            url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
        }
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        }
        maven { url = uri("https://jitpack.io") }
    }
    dependencies {
        compileOnly("org.spigotmc:spigot-api:$spigotVersion")
        compileOnly("com.github.Onyxium-Studio:Reactant:1b58177719")
        compileOnly(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    }

    tasks.withType<KotlinCompile>().configureEach {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_25)
        }
    }

    tasks.withType<JavaCompile>().configureEach {
        options.release.set(25)
    }

    val shadowJar = tasks.named<Jar>("shadowJar") {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
        //exclude("kotlin*", "junit*", "org.junit*", "org.hamcrest*", "org.intellij*", "org.jetbrains*")
        //relocate("org.from.package", "org.target.package")
    }

    val sourcesJar = tasks.register<Jar>("sourcesJar") {
        dependsOn(JavaPlugin.CLASSES_TASK_NAME)
        archiveClassifier.set("sources")
        from(sourceSets.main.get().allSource)
    }

    val jar = tasks.named<Jar>("jar")

    val deployPlugin = tasks.register<Copy>("deployPlugin") {
        dependsOn(shadowJar)
        System.getenv("PLUGIN_DEPLOY_PATH")?.let {
            from(shadowJar)
            into(it)
        }
    }

    tasks.named("build") {
        arrayOf(
            sourcesJar
            , shadowJar
            , deployPlugin
        ).forEach { dependsOn(it) }
    }
}
dependencies {
    // compileOnly(kotlin("stdlib-jdk8"))
}
repositories {
    mavenCentral()
}