import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4/samples
 */

plugins {
    val kotlinVersion: String = "1.9.20"
    kotlin("jvm") version kotlinVersion
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

allprojects {
    apply {
        plugin("org.jetbrains.kotlin.jvm")
        plugin("com.github.johnrengelman.shadow")
    }

    group = "io.github.clayclaw"

    val spigotVersion = "1.18.2-R0.1"

    repositories {
        mavenCentral()
        maven {
            url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
        }
        maven {
            url = uri("https://oss.sonatype.org/content/repositories/snapshots")
        }
        maven { url = uri("https://jitpack.io") }
    }
    dependencies {
        compileOnly("org.spigotmc:spigot-api:${spigotVersion}-SNAPSHOT")
        compileOnly("com.github.Onyxium-Studio:Reactant:5b8cbc65d0")
        compileOnly(fileTree(mapOf("dir" to "libs", "include" to listOf("*.jar"))))
    }

    sourceSets.main {
        java.srcDirs("build/generated/ksp/main/kotlin")
    }

    val shadowJar = (tasks["shadowJar"] as com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).apply {
        exclude("kotlin*", "junit*", "org.junit*", "org.hamcrest*", "org.intellij*", "org.jetbrains*")
        //relocate("org.from.package", "org.target.package")
    }

    val sourcesJar by tasks.registering(Jar::class) {
        dependsOn(JavaPlugin.CLASSES_TASK_NAME)
        archiveClassifier.set("sources")
        from(sourceSets.main.get().allSource)
    }

    val jar = (tasks["jar"] as Jar).apply {}

    val deployPlugin by tasks.registering(Copy::class) {
        dependsOn(jar)
        System.getenv("PLUGIN_DEPLOY_PATH")?.let {
            from(jar)
            into(it)
        }
    }

    val build = (tasks["build"] as Task).apply {
        arrayOf(
            sourcesJar
            , shadowJar
            , deployPlugin
        ).forEach { dependsOn(it) }
    }
}
dependencies {
    implementation(kotlin("stdlib-jdk8"))
}
repositories {
    mavenCentral()
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}