name: LightCargo-KtsEngine
main: io.github.clayclaw.lightcargo.kts.environment.bukkit.BootstrapPlugin
version: 0.0.1
description: LightCargo KtsEngine plugin
author: ButterJar#0149
softdepend:
  - Reactant
commands:
  rcs:
    description: Recompile and evaluate scripts
  rds:
    description: Rediscover and compile scripts
  rs:
    description: Reload changed scripts
  fullrs:
    description: Fully reload scripts
libraries:
  - org.jetbrains.kotlin:kotlin-script-runtime:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-common:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-jvm:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-jvm-host:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-dependencies:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-dependencies-maven:1.6.10
  - org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:1.6.10