name: LightCargo-KtsEngine
main: io.github.clayclaw.lightcargo.kts.environment.bukkit.BootstrapPlugin
version: 0.0.1
description: LightCargo KtsEngine plugin
author: ButterJar#0149
softdepend:
  - Reactant
commands:
  rcs:
    description: Recompile and evaluate scripts
  rds:
    description: Rediscover and compile scripts
  rs:
    description: Reload changed scripts
  fullrs:
    description: Fully reload scripts